배포8

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -29,6 +29,13 @@ jobs:
       - name: Build Spring Boot project with Gradle
         run: ./gradlew clean build -x test -Dspring.profiles.active=prod
 
+      - name: Check if JAR file exists
+        run: |
+          if [ ! -f "build/libs/onmom-0.0.1-SNAPSHOT.jar" ]; then
+            echo "Error: JAR file not found!"
+            exit 1
+          fi
+
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
